#!/usr/bin/env python3
"""extract_stencils.py — turn a compiled stencil .o into a C header.

Reads a relocatable Mach-O object (arm64-apple-darwin; ELF support is a TODO)
produced from tools/jit/stencils.c, and for each `_zjs_stencil_*` function emits
its raw machine-code bytes plus its relocation records (the "holes"). The JIT
runtime memcpy's a stencil per bytecode instruction and patches the holes.

Usage:
    extract_stencils.py <input.o> <output.h>

The CPython Tools/jit model. On arm64-apple-darwin the holes materialize through
the GOT (adrp@GOTPAGE / ldr@GOTPAGEOFF, as a same-symbol pair) plus a BRANCH26
continuation; see docs/jit-impl-notes.md. We emit those reloc kinds verbatim and
let the stitcher build a synthetic GOT.
"""
import struct
import sys

MH_MAGIC_64   = 0xFEEDFACF
LC_SEGMENT_64 = 0x19
LC_SYMTAB     = 0x02
N_SECT        = 0x0E   # n_type & N_TYPE == N_SECT (defined in a section)
N_TYPE        = 0x0E

# ARM64 Mach-O relocation types (mach-o/arm64/reloc.h)
ARM64_RELOC = {
    0:  "UNSIGNED",
    1:  "SUBTRACTOR",
    2:  "BRANCH26",
    3:  "PAGE21",
    4:  "PAGEOFF12",
    5:  "GOT_LOAD_PAGE21",
    6:  "GOT_LOAD_PAGEOFF12",
    7:  "POINTER_TO_GOT",
    10: "ADDEND",
}


def parse_macho(data):
    magic, = struct.unpack_from("<I", data, 0)
    if magic != MH_MAGIC_64:
        sys.exit(f"extract_stencils: not a 64-bit little-endian Mach-O ({magic:#x})")
    ncmds, = struct.unpack_from("<I", data, 16)
    off = 32  # sizeof(mach_header_64)
    text = None
    symtab = None
    for _ in range(ncmds):
        cmd, cmdsize = struct.unpack_from("<II", data, off)
        if cmd == LC_SEGMENT_64:
            nsects, = struct.unpack_from("<I", data, off + 64)
            sec = off + 72  # past segment_command_64 header
            for _s in range(nsects):
                sname = data[sec:sec + 16].split(b"\0")[0]
                addr, size = struct.unpack_from("<QQ", data, sec + 32)
                offset, align, reloff, nreloc = struct.unpack_from("<IIII", data, sec + 48)
                if sname == b"__text":
                    text = dict(addr=addr, size=size, offset=offset,
                                reloff=reloff, nreloc=nreloc)
                sec += 80  # sizeof(section_64)
        elif cmd == LC_SYMTAB:
            symoff, nsyms, stroff, strsize = struct.unpack_from("<IIII", data, off + 8)
            symtab = dict(symoff=symoff, nsyms=nsyms, stroff=stroff, strsize=strsize)
        off += cmdsize
    if text is None or symtab is None:
        sys.exit("extract_stencils: missing __text or symtab")
    return text, symtab


def parse_symbols(data, symtab):
    syms = []
    for i in range(symtab["nsyms"]):
        base = symtab["symoff"] + i * 16  # sizeof(nlist_64)
        n_strx, n_type, n_sect, n_desc, n_value = struct.unpack_from("<IBBHQ", data, base)
        name = data[symtab["stroff"] + n_strx:].split(b"\0")[0].decode()
        syms.append(dict(name=name, type=n_type, sect=n_sect, value=n_value))
    return syms


def parse_relocs(data, text):
    relocs = []
    for i in range(text["nreloc"]):
        base = text["reloff"] + i * 8  # sizeof(relocation_info)
        r_address, second = struct.unpack_from("<iI", data, base)
        relocs.append(dict(
            addr=r_address,
            symnum=second & 0xFFFFFF,
            pcrel=(second >> 24) & 1,
            length=(second >> 25) & 3,
            extern=(second >> 27) & 1,
            type=(second >> 28) & 0xF,
        ))
    return relocs


def main():
    if len(sys.argv) != 3:
        sys.exit("usage: extract_stencils.py <input.o> <output.h>")
    data = open(sys.argv[1], "rb").read()
    text, symtab = parse_macho(data)
    syms = parse_symbols(data, symtab)
    relocs = parse_relocs(data, text)

    # Stencil functions, ordered by their offset in __text. Sizes are derived
    # from the gap to the next stencil (last runs to the section end).
    stencils = sorted(
        [s for s in syms if s["name"].startswith("_zjs_stencil_")
         and (s["type"] & N_TYPE) == N_SECT],
        key=lambda s: s["value"])
    if not stencils:
        sys.exit("extract_stencils: no _zjs_stencil_* symbols found")
    bounds = []
    for i, s in enumerate(stencils):
        start = s["value"]
        end = stencils[i + 1]["value"] if i + 1 < len(stencils) else text["size"]
        bounds.append((s["name"], start, end))

    body = data[text["offset"]:text["offset"] + text["size"]]

    out = []
    out.append("// GENERATED by tools/jit/extract_stencils.py — do not edit.")
    out.append("// Copy-and-patch stencils: machine-code bytes + hole relocations.")
    out.append("#pragma once")
    out.append("#include <stdint.h>")
    out.append("")
    out.append("typedef struct { uint32_t offset; uint8_t kind; const char *sym; } JitHole;")
    out.append("typedef struct { const char *name; const uint8_t *code; uint32_t code_len;")
    out.append("                 const JitHole *holes; uint32_t nholes; } JitStencil;")
    out.append("")
    # reloc-kind enum mirrored as small ints; the stitcher switches on them.
    out.append("enum { JIT_HOLE_BRANCH26=2, JIT_HOLE_GOT_PAGE21=5, JIT_HOLE_GOT_PAGEOFF12=6 };")
    out.append("")

    summary = []
    table_entries = []
    for name, start, end in bounds:
        opname = name[len("_zjs_stencil_"):]
        chunk = body[start:end]
        # Holes whose address falls in this stencil, offset-relative to it.
        hs = []
        for r in relocs:
            if start <= r["addr"] < end:
                sym = syms[r["symnum"]]["name"] if r["extern"] else "<local>"
                hs.append((r["addr"] - start, r["type"], sym))
        hs.sort()
        cbytes = ", ".join(f"0x{b:02x}" for b in chunk)
        out.append(f"static const uint8_t STENCIL_{opname}_code[] = {{ {cbytes} }};")
        if hs:
            hole_inits = ", ".join(
                f'{{ {off}, {kind}, "{sym}" }}' for (off, kind, sym) in hs)
            out.append(f"static const JitHole STENCIL_{opname}_holes[] = {{ {hole_inits} }};")
            holes_ref = f"STENCIL_{opname}_holes"
            nholes = len(hs)
        else:
            holes_ref = "0"
            nholes = 0
        out.append("")
        table_entries.append(
            f'  {{ "{opname}", STENCIL_{opname}_code, sizeof(STENCIL_{opname}_code), '
            f'{holes_ref}, {nholes} }},')
        summary.append((opname, len(chunk), hs))

    out.append("static const JitStencil JIT_STENCILS[] = {")
    out.extend(table_entries)
    out.append("};")
    out.append(f"enum {{ JIT_STENCIL_COUNT = {len(bounds)} }};")
    out.append("")

    open(sys.argv[2], "w").write("\n".join(out))

    # Human-readable summary to stderr for cross-checking vs `otool -rv`.
    print(f"[extract] {sys.argv[1]} -> {sys.argv[2]}  ({len(bounds)} stencils)", file=sys.stderr)
    for opname, clen, hs in summary:
        kinds = ", ".join(f"+{off:#x}:{ARM64_RELOC.get(k, k)}:{sym}" for (off, k, sym) in hs)
        print(f"  {opname:14s} {clen:3d}B  holes=[{kinds}]", file=sys.stderr)


if __name__ == "__main__":
    main()
