#!/usr/bin/env python3
"""Embed a JS source file as a C string literal in a .gen.h header.

Used by the stdlib pure-JS bootstrap (`src/stdlib/web_*.js`,
`src/stdlib/node_*.js`) to replace the inline `"...\\n"` C-string
fragments inside the corresponding .zc files. The .zc file then just
`#include`s the generated header to get the source as a const char[].

Usage:
    embed_js.py <input.js> <output.gen.h> <SYMBOL_NAME>

The output declares:
    static const char SYMBOL_NAME[];
    static const size_t SYMBOL_NAME_LEN;

The header is reproducible — re-running it on unchanged input produces
identical output, so make-style dependency tracking works.
"""
import sys
from pathlib import Path


def emit(input_path: Path, output_path: Path, symbol: str) -> None:
    source = input_path.read_bytes().decode("utf-8")
    lines = source.split("\n")
    # Drop a trailing empty line so the embedded literal doesn't end in
    # a spurious "\n" — but only if the file did end with a newline,
    # not if it ends mid-line (rare; would lose data).
    has_trailing_nl = source.endswith("\n")
    if has_trailing_nl:
        lines = lines[:-1]

    out: list[str] = []
    out.append("// Auto-generated by tools/embed_js.py from")
    out.append(f"// {input_path.as_posix()} — DO NOT EDIT.")
    out.append("// Re-run `make stdlib-embed` (or any make target) to regenerate.")
    out.append("")
    out.append(f"static const char {symbol}[] =")
    for i, line in enumerate(lines):
        escaped = (
            line.replace("\\", "\\\\")
            .replace("\"", "\\\"")
            .replace("\t", "\\t")
        )
        # Always emit a trailing \n in the embedded string, matching
        # how the original `"...\n"` per-line shape worked.
        out.append(f'    "{escaped}\\n"')
    # Terminate the chain.
    out[-1] = out[-1] + ";"
    out.append("")
    out.append(f"static const size_t {symbol}_LEN = sizeof({symbol}) - 1;")
    out.append("")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(out), encoding="utf-8")


def main() -> int:
    if len(sys.argv) != 4:
        sys.stderr.write(__doc__)
        return 2
    input_path = Path(sys.argv[1])
    output_path = Path(sys.argv[2])
    symbol = sys.argv[3]
    if not input_path.exists():
        sys.stderr.write(f"embed_js.py: input not found: {input_path}\n")
        return 1
    emit(input_path, output_path, symbol)
    return 0


if __name__ == "__main__":
    sys.exit(main())
